apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  labels:
    application: prometheus-node-exporter
    version: v0.12.0
    component: node-exporter
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: prometheus-node-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        application: prometheus-node-exporter
        version: v0.12.0
        component: node-exporter
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      serviceAccountName: system
      containers:
      - image: prom/node-exporter:0.12.0
        name: prometheus-node-exporter
        ports:
        - name: prom-node-exp
          containerPort: 9100
          hostPort: 9100
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 25m
            memory: 25Mi
        securityContext:
          privileged: true
      hostNetwork: true
      hostPID: true
